### ISSUE TITLE
Не хватает некоторых символов

### ISSUE THREAD

**Issue by silentroach** [shoorick/russian-road-sign-font#2]
Спасибо за шрифт, очень круто!

Но заметил, что не хватает некоторых символов: % ! ?

**Comment by shoorick** [comment]
Вопросительный и восклицательный знаки точно должны быть. В ноябре прошлого года были:

![Надписи](http://shoorick.ru/wp-content/uploads/2017/11/latin-sample-roadsignfont.png)

Насчёт знака процента не помню — надо будет проверить.

**Comment by shoorick** [comment]
Ссылка вдогонку — http://shoorick.ru/category/font/

**Comment by silentroach** [comment]
Поторопился, извините, из перечисленных не хватает действительно только знака процента

<img width="240" alt="screen shot 2018-06-14 at 13 43 26" src="https://user-images.githubusercontent.com/166803/41407734-03f08d0a-6fd9-11e8-9b23-9a354ac62991.png">

**Comment by silentroach** [comment]
Посмотрите, если не сложно? :}
Пробел еще великоват, мне кажется - он действительно таким должен быть?

**Comment by shoorick** [comment]
Процента в шрифте ещё нет — его нет и в стандарте. Однако в стандарте действительно есть знаки крутого спуска и подъёма — попробую в ближайшее время срисовать оттуда.

**Comment by shoorick** [comment]
На знаке процент страшненький — пришлось нарисовать слегка иначе. Заодно нарисовал ‰ и ‱.

Ширина пробелов и межсимвольных расстояний — тема отдельной задачи: похоже, весь шрифт надо перетряхивать.
